### ISSUE TITLE
Undefined index ipay88 payment page

### ISSUE THREAD

**Issue by neilmaynard** [aifaiz/ipay88-woocommerce#14]
Good day!

I was working on my current project in wordpress and was enlightened to use the ipay88 payment gateway plugin in woocommerce. I followed the installation instructions provided and yet these things pop out on my local. Below links are some screenshots on the page. Your help will be appreciated. Thank you!

https://snag.gy/NAK4Ys.jpg
https://snag.gy/oJ0cUa.jpg
https://snag.gy/jzh3Kn.jpg
https://snag.gy/gJN4TW.jpg
https://snag.gy/O3RF9A.jpg
https://snag.gy/YJcRLl.jpg

**Comment by aifaiz** [comment]
hey man. thanks for using this plugin!
btw, im sorry for the late reply. cz im totaly out of hand with other things.

for your particullar issue. i think it is because you havent installed `woocommerce` ? try uninstalling the plugin. install woocommerce first. then install the plugin again.

Regards,
AiFAiZ
https://hamizulfaiz.com
