### ISSUE TITLE
Page Template Not Showing Up

### ISSUE THREAD

**Issue by adriansabah** [aifaiz/ipay88-woocommerce#4]
Hi Brother,

It was perfect timing for me finding your plugin.
I'm helping out a business owner with his iPay88 processing on a wp site.
Maybe it is because I am using the Divi theme from Elegantthemes.com
but the page template does not show up - so I get a blank payment page.

Any tips on how I can make this work?

Adrian Lee

**Comment by aifaiz** [comment]
hi. could you screenshot your page that used to assign the template? it would help to see the template listing to identify the bug

**Comment by aifaiz** [comment]
after doing a lot of testing. it think this issue is related with wp 4.7 which has an updated way to access template files. I have updated the code to include the latest way on `Page Template` include. refer to this commit [0ca92da](https://github.com/aifaiz/ipay88-woocommerce/commit/0ca92dab002f67d5fefd7f16df474af7b32f4fc6)

**Comment by adriansabah** [comment]
Hi,
Sorry for the delay and awesome quick answer from you.

1) I tested it on divi theme (elegantthemes.com) but get a blank payment page.
The template selection shows up on the page but is blank when viewed.
In the plugin settings, instead of Page ID, it shows "Array" (attachment 1).

![attachment 1_ipay88 plugin error](https://cloud.githubusercontent.com/assets/26326159/23858867/e0a69dee-083c-11e7-985a-7e4ba2477aba.jpg)

2) I tried it on wordpress Twenty Seventeen theme but got this error message (see attachment 2)

![attachment 2_error 2017 theme](https://cloud.githubusercontent.com/assets/26326159/23858868/e0ab4e16-083c-11e7-8149-ef35007a5cc8.jpg)

I just thought you might be interested to know. I just build websites and don't know much coding, so I can't really tell you much.

**Comment by aifaiz** [comment]
Alright. i had make some fix and ammendment to the codes. you can try to delete the previous version and install this new one. see if everything is okay.

the reason is because the template are not parsing properly to the correct path for payment. it is resolved with tweaks of the path and i moved some files to the correct path.

regarding the dropdown. it is now fixed with dropdown of pages list so you can just select the `Payment` page instead using the page ID
